services:
  # Twenty CRM Server
  twenty-server:
    image: twentycrm/twenty:latest
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - SERVER_URL=https://crm.app.earthcare.network
      - FRONT_BASE_URL=https://crm.app.earthcare.network
      - PG_DATABASE_URL=postgres://postgres:KeepGoin!!!@postgres:5432/twenty
      - REDIS_URL=redis://redis:6379
      - APP_SECRET=earth-care-network-app-secret-2025-super-secure-key
      - SUPPORT_EMAIL=support@earthcare.network
      - ENABLE_DB_MIGRATIONS=true
      - PORT=3000
    ports:
      - "3001:3000"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - earthcare-network
    volumes:
      - twenty-server-data:/app/packages/twenty-server/.local-storage

  # Twenty CRM Worker  
  twenty-worker:
    image: twentycrm/twenty:latest
    restart: unless-stopped
    command: yarn worker:prod
    environment:
      - NODE_ENV=production
      - SERVER_URL=https://crm.app.earthcare.network
      - FRONT_BASE_URL=https://crm.app.earthcare.network
      - PG_DATABASE_URL=postgres://postgres:KeepGoin!!!@postgres:5432/twenty
      - REDIS_URL=redis://redis:6379
      - APP_SECRET=earth-care-network-app-secret-2025-super-secure-key
      - SUPPORT_EMAIL=support@earthcare.network
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - earthcare-network
    volumes:
      - twenty-server-data:/app/packages/twenty-server/.local-storage

  # PostgreSQL Database
  postgres:
    image: postgis/postgis:16-3.4-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_DB=twenty
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=KeepGoin!!!
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - postgres_data:/var/lib/postgresql/data/pgdata
    networks:
      - earthcare-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d twenty"]
      interval: 30s
      timeout: 10s
      retries: 5

  # Redis Cache
  redis:
    image: redis:7-alpine
    restart: unless-stopped
    networks:
      - earthcare-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  postgres_data:
    driver: local
  twenty-server-data:
    driver: local

networks:
  earthcare-network:
    driver: bridge