services:
  # EarthCare Directory (React App)
  directory:
    build:
      context: ./directory
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - REACT_APP_CRM_API_URL=https://crm.app.earthcare.network/graphql
      - REACT_APP_CRM_BASE_URL=https://crm.app.earthcare.network
      - NODE_ENV=production
    ports:
      - "3003:80"
    networks:
      - dokploy-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.directory.rule=Host(`app.earthcare.network`)"
      - "traefik.http.routers.directory.entrypoints=websecure"
      - "traefik.http.routers.directory.tls.certresolver=letsencrypt"
      - "traefik.http.services.directory.loadbalancer.server.port=80"

networks:
  dokploy-network:
    external: true
