services:
  # EarthCare Directory (React App) - Working Service
  directory:
    build:
      context: ./directory
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - REACT_APP_CRM_API_URL=https://crm.app.earthcare.network/graphql
      - REACT_APP_CRM_BASE_URL=https://crm.app.earthcare.network
      - NODE_ENV=production
    ports:
      - "3003:80"
    networks:
      - earthcare-network

  # PostgreSQL Database
  postgres:
    image: postgis/postgis:16-3.4-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_DB=twenty
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=KeepGoin!!!
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - postgres_data:/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    networks:
      - earthcare-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d twenty"]
      interval: 30s
      timeout: 10s
      retries: 5

  # Redis Cache
  redis:
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - earthcare-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  postgres_data:
    driver: local

networks:
  earthcare-network:
    driver: bridge