#!/bin/bash

# EarthCare Network - Dokploy Configuration Guide
echo "🎯 EarthCare Network Dokploy Configuration Guide"
echo "=================================================="
echo ""
echo "✅ Current Status:"
echo "   - Dokploy Dashboard: http://157.230.173.94:3000"
echo "   - Directory Service: ✅ Running on port 8080"
echo "   - Database (PostgreSQL): ✅ Running on port 5432"
echo "   - Cache (Redis): ✅ Running on port 6379"
echo "   - MCP Server: Starting on port 8090"
echo ""
echo "🔧 Dokploy Login Credentials:"
echo "   Email: arye@earthcare.network"
echo "   Password: KeepGoin!!!"
echo ""
echo "📋 Step-by-step Dokploy Configuration:"
echo ""
echo "1️⃣  Open Dokploy Dashboard: http://157.230.173.94:3000"
echo "2️⃣  Login with the credentials above"
echo "3️⃣  Create new project: 'earthcare-network'"
echo "4️⃣  Add applications:"
echo ""
echo "   📱 APPLICATION 1: EarthCare Directory"
echo "   ────────────────────────────────────"
echo "   • Name: earthcare-directory"
echo "   • Type: Docker Compose"
echo "   • Source: Upload docker-compose.simple.yml"
echo "   • Domain: app.earthcare.network"
echo "   • Port: 8080"
echo "   • SSL: Enable Let's Encrypt"
echo ""
echo "   🏢 APPLICATION 2: Twenty CRM (External)"
echo "   ────────────────────────────────────"
echo "   • Name: twenty-crm"
echo "   • Type: External Service"
echo "   • Target: http://localhost:3001"
echo "   • Domain: crm.app.earthcare.network"
echo "   • Additional Domain: app.crm.app.earthcare.network"
echo "   • SSL: Enable Let's Encrypt"
echo ""
echo "   🧪 APPLICATION 3: MCP Testing Server"
echo "   ────────────────────────────────────"
echo "   • Name: mcp-server"
echo "   • Type: Docker"
echo "   • Image: node:18-alpine"
echo "   • Command: sh -c 'npm install axios express cors && node server.js'"
echo "   • Port: 8080"
echo "   • Volume: /opt/earthcare-deployment/mcp-server:/app"
echo "   • Environment:"
echo "     CRM_URL=https://crm.app.earthcare.network"
echo "     DIRECTORY_URL=https://app.earthcare.network"
echo ""
echo "🌐 Domain Configuration (DNS already set):"
echo "   ✅ app.earthcare.network → Directory"
echo "   ✅ crm.app.earthcare.network → Twenty CRM"  
echo "   ✅ app.crm.app.earthcare.network → Twenty CRM"
echo "   ✅ *.crm.app.earthcare.network → Wildcard SSL"
echo ""
echo "🔧 Environment Variables for Twenty CRM:"
echo "   SERVER_URL=https://crm.app.earthcare.network"
echo "   FRONT_BASE_URL=https://crm.app.earthcare.network"
echo "   PG_DATABASE_URL=postgres://twenty:earthcare_pg_2024_secure@157.230.173.94:5432/default"
echo "   REDIS_URL=redis://157.230.173.94:6379"
echo "   CORS_ALLOWED_ORIGINS=https://crm.app.earthcare.network,https://app.crm.app.earthcare.network"
echo ""
echo "🧪 Testing URLs (after configuration):"
echo "   • Directory: https://app.earthcare.network"
echo "   • CRM: https://crm.app.earthcare.network"
echo "   • CRM Workspace: https://app.crm.app.earthcare.network"
echo "   • MCP Testing: curl https://mcp.earthcare.network/test-all"
echo ""
echo "📝 Post-Configuration Tasks:"
echo "   1. Install Twenty CRM separately or configure external source"
echo "   2. Test all SSL certificates"
echo "   3. Run full end-to-end test via MCP server"
echo "   4. Configure CI/CD pipeline for future deployments"
echo ""
echo "🚀 Quick Test Commands:"
echo "   curl -I http://157.230.173.94:8080  # Directory test"
echo "   curl -I http://157.230.173.94:3000  # Dokploy dashboard"
echo ""
echo "💡 Need Help? Check logs with:"
echo "   ssh root@157.230.173.94 'docker logs earthcare-deployment-directory-1'"
echo ""

# Test current deployments
echo "🔍 Current Service Status:"
echo "─────────────────────────"

# Test Directory
if curl -s --max-time 5 http://157.230.173.94:8080 > /dev/null; then
    echo "✅ Directory Service: Running at http://157.230.173.94:8080"
else
    echo "❌ Directory Service: Not accessible"
fi

# Test Dokploy
if curl -s --max-time 5 http://157.230.173.94:3000 > /dev/null; then
    echo "✅ Dokploy Dashboard: Running at http://157.230.173.94:3000"
else
    echo "❌ Dokploy Dashboard: Not accessible"
fi

echo ""
echo "🎉 Ready for Dokploy configuration!"
echo "📖 Open http://157.230.173.94:3000 to get started"