#!/bin/bash

# Local deployment script to upload files to Digital Ocean droplet
# Run this script from your local machine

set -e

SERVER_IP="157.230.173.94"
SERVER_USER="root"
SERVER_PASS="BrG5e=n_Nd4B!zP"
LOCAL_DIR="/Users/aryeshabtai/earth care network/twenty"

echo "🚀 Deploying EarthCare Network to Digital Ocean..."

# Upload deployment files to server
echo "📤 Uploading deployment files..."

# Upload main deployment files
sshpass -p "$SERVER_PASS" scp "$LOCAL_DIR/docker-compose.production.yml" "$SERVER_USER@$SERVER_IP:/tmp/docker-compose.yml"
sshpass -p "$SERVER_PASS" scp "$LOCAL_DIR/.env.production" "$SERVER_USER@$SERVER_IP:/tmp/.env"
sshpass -p "$SERVER_PASS" scp "$LOCAL_DIR/deploy.sh" "$SERVER_USER@$SERVER_IP:/tmp/deploy.sh"

# Upload directory files
sshpass -p "$SERVER_PASS" scp -r "$LOCAL_DIR/directory" "$SERVER_USER@$SERVER_IP:/tmp/"

echo "🔧 Running deployment on server..."

# Connect to server and run deployment
sshpass -p "$SERVER_PASS" ssh "$SERVER_USER@$SERVER_IP" << 'EOF'
# Make deploy script executable and run it
chmod +x /tmp/deploy.sh
/tmp/deploy.sh

# Move files to proper locations
cd /opt/earthcare
cp /tmp/docker-compose.yml .
cp /tmp/.env .
cp -r /tmp/directory/* ./directory/

# Start services
echo "🚀 Starting EarthCare Network services..."
docker-compose down 2>/dev/null || true
docker-compose up -d

# Wait for services to start
echo "⏳ Waiting for services to start..."
sleep 30

# Check service status
echo "📊 Service status:"
docker-compose ps

echo ""
echo "✅ EarthCare Network deployment complete!"
echo ""
echo "🌐 Your applications are now available at:"
echo "   - EarthCare Directory: https://app.earthcare.network"
echo "   - Twenty CRM: https://crm.app.earthcare.network"
echo "   - Traefik Dashboard: http://157.230.173.94:8080"
echo ""
echo "📝 Note: SSL certificates will be automatically generated by Let's Encrypt"
echo "    It may take a few minutes for HTTPS to be available."
EOF

echo "🎉 Deployment completed successfully!"